### ISSUE TITLE
Systemd 229 support

### ISSUE THREAD

**Issue by vaijab** [ledbettj/systemd-journal#60]
I am just raising this issue more like a question. We are using this library, but it does not seem to work with systemd 229.

Have you tested it with latest version of systemd? We're using v1.2.2 of this library.

**Comment by ledbettj** [comment]
Hi,
I haven't seen any issues with using `systemd-journal` with v229.  Can you provide more information about what sort of behavior you are seeing?

**Comment by vaijab** [comment]
@ledbettj thanks, I just wanted to confirm that you have tested it with v229. I will try to spend a little more time and let you know.
