### ISSUE TITLE
seek(:tail) does not work

### ISSUE THREAD

**Issue by richm** [ledbettj/systemd-journal#64]
`seek(:tail)` does not work.  It does not return the last entry in the journal.  For example, run this script:
```
require 'systemd/journal'
require 'time'

now = Time.now
j = Systemd::Journal.new(path: '/var/log/journal')
j.seek(:tail)
if rc = j.move_next
    puts "how is it possible to move_next from the tail"
end
diff = now - j.current_entry.realtime_timestamp
puts "journal tail is #{diff} seconds or #{diff/86400} days behind now"
count = 1
while rc
    rc = j.move_next
    count = count + 1
end
diff = now - j.current_entry.realtime_timestamp
puts "we finally got to the tail after #{count} entries - time #{j.current_entry.realtime_timestamp} - last entry is #{diff} seconds behind now"
```

On my Fedora 24 system, I get the following output:
```
how is it possible to move_next from the tail
journal tail is 7957356.183605957 seconds or 92.09902990284672 days behind now
we finally got to the tail after 39 entries - time 2017-01-06 15:28:12 -0700 - last entry is 80.451257957 seconds behind now
```

That is, when doing `seek(:tail)`, it is really 39 entries behind the actual tail.

Compare this to the behavior of `journalctl -f` which returns the last entry

**Comment by ledbettj** [comment]
Hi, thanks for opening the issue.

According to the upstream documentation, `seek(:tail)` positions the read pointer immediately after the last item in the journal.  As such, you should call `move_previous` before reading any entries. Calling `move_next` will cause you to [see random entries](https://bugs.freedesktop.org/show_bug.cgi?id=64614).

 It seems that this is not mentioned in the gem documentation 😨 , so we can probably improve that here.

**Comment by ledbettj** [comment]
In my testing if you add `move_previous` immediately after your `seek(:tail)` in your test program you will see: 

> we finally got to the tail after 1 entries

Let me know if this is not the case for you.

**Comment by richm** [comment]
Works for me.  Thanks!
