### ISSUE TITLE
No error thrown when trying to read journals that have unsupported features.

### ISSUE THREAD

**Issue by aerostitch** [ledbettj/systemd-journal#71]
Example, I was trying to read a remote journalctl mounted in a pod. The journal was generated with systemd 233 in coreos (that has LZ4 activated). The container was a xenial that had systemd 229 that did not support LZ4.
journalctl on a journal file was throwing:
```# journalctl -D /var/log/journal
An error was encountered while opening journal file /var/log/journal/24dd9a9aa0e0460a8df160846c02d699, ignoring file.
Journal file /var/log/journal/379315b5ccb6439582865fc63665ada8/system@2855f01a1b7d40aabed9794457fa38d7-00000000001a0a6a-00055269c17f4183.journal uses an unsupported feature, ignoring file.
-- No entries --
```
Using the examples in the readme didn't throw any error. It would be good to have at least a warning when you encounter those kind of issues.
Thanks

**Comment by ledbettj** [comment]
Hi,

Thanks for the report.  I'll dig into this and see if we can catch it somehow.

**Comment by ledbettj** [comment]
Looking at the [source](https://github.com/systemd/systemd/blob/master/src/shared/journal-util.c#L135-L137) of where this message comes from, it looks like it's inspecting an [internal field](https://github.com/systemd/systemd/blob/dd8352659c9428b196706d04399eec106a8917ed/src/journal/journal-internal.h#L136) on the journal struct that's not exposed via the `sd_journal_*` api.

So sadly I don't know if it's possible to catch this case using any existing `libsystemd` interface :(

**Comment by aerostitch** [comment]
Ok. Do you think you could display this error message or does the libsystemd doesn't throw it at all?
Just wondering if it's an error that's silenced down the line or if tools like journalctl check the features stored in the header of the journal file and compare them to the list of their own features to throw that error.

**Comment by ledbettj** [comment]
Closing for now as this is not possible without support from libsystemd
