### ISSUE TITLE
Systemd::Journal.message fails when the message contains % characters

### ISSUE THREAD

**Issue by pschyska** [ledbettj/systemd-journal#76]
When a single % is the last character in a message, I get the error "cannot allocate memory" 

> [2] pry(main)> Systemd::Journal.message(message: '%')
> Systemd::JournalError: Cannot allocate memory
> from .rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/systemd-journal-1.2.3/lib/systemd/journal/writable.rb:82:in `message'
> [3] pry(main)> Systemd::Journal.message(message: '%%')
> nil
> [4] pry(main)> Systemd::Journal.message(message: '%%%')
> Systemd::JournalError: Cannot allocate memory
> from .rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/systemd-journal-1.2.3/lib/systemd/journal/writable.rb:82:in `message'

On some patterns, the ruby interpreter segfaults:

> [7] pry(main)> Systemd::Journal.message(message: 'a%u')
> .rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ffi-1.9.18/lib/ffi/variadic.rb:56: [BUG] Segmentation fault at 0x00000000000000
> ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

Backtrace: https://gist.github.com/pschyska/f54824d7af1c8a86a918b84098f97660

**Comment by ledbettj** [comment]
Hi, thanks for reporting.  It turns out that under the hood `sd_journal_send` supports printf-style formatting; as a result, we definitely need to escape any `%`s that we pass in by converting to double `%%`.  I'll add a fix soon.

**Comment by pschyska** [comment]
we do a `.gsub('%', '%%')` on every field now. Thanks for the gem btw, it's a great help!

**Comment by ledbettj** [comment]
We'll do this `gsub` by default in 1.3.1.
