### ISSUE TITLE
Intermittent failure with Native.sd_journal_print

### ISSUE THREAD

**Issue by djberg96** [ledbettj/systemd-journal#89]
There's a hard to track down segfault that was reported:

https://github.com/ManageIQ/manageiq/pull/20004

```
Sometimes the journald logger segfaults, remove it until this can be further investigated:
/usr/local/lib/ruby/gems/2.6.0/gems/systemd-journal-1.4.1/lib/systemd/journal/writable.rb:69: [BUG] Segmentation fault at 0x0000000000000c91
```

So I tried fuzzing, and I see a bunch of segfaults:

```
# gem install fuzzbert
# > fuzzbert fuzz_sd_journal_print.rb

require 'fuzzbert'
require 'systemd/journal'

level = 7 # debug

fuzz "Systemd::Journal::Native.sd_journal_print" do
  deploy do |data|
    begin
      Systemd::Journal::Native.sd_journal_print(level, data)
    rescue Exception
      # ok
    end
  end

  data "completely random" do
    FuzzBert::Generators.random
  end
end
```

Now, I don't know if this type of fuzzing is "legitimate", but I thought I would at least report it to see what you think.

**Comment by ledbettj** [comment]
If you check the manpage for `sd_journal_print` you'll see it accepts a format specifier, like printf;  it's not surprising to me that you can cause the native code to crash; something like this will segfault reliably and for good reason:

```ruby
Systemd::Journal::Native.sd_journal_print(7, "%s %s")
```

I would guess that the simplest solution is to ensure that `%` signs are escaped; you can see that this is done [here](https://github.com/ledbettj/systemd-journal/blob/master/lib/systemd/journal/writable.rb#L77) for `sd_journal_send` which is also a variadic function.

As to why the `Systemd::Journal.print` method doesn't do this, I'm not sure; it may be that I did not change it to maintain compatibility with the prior version of the gem that only exposed that functionality?

**Comment by ledbettj** [comment]
Ultimately I think it makes sense that the `Systemd::Journal.print` should escape `%` signs for you, since there's no real reason not to do it -- we don't accept additional arguments, so there's no upside to allowing it, and the downside is clearly a segfault.

**Comment by ledbettj** [comment]
#90

**Comment by djberg96** [comment]
@ledbettj thanks!

**Comment by ledbettj** [comment]
I pushed https://github.com/ledbettj/systemd-journal/releases/tag/v1.4.2 with this fix.

**Comment by djberg96** [comment]
@ledbettj thanks again! wow, that was fast.

Just FYI for anyone reading this, I ran the fuzzbert program above for about 5 minutes and there were no crashes. :)
