### ISSUE TITLE
SIGABRT on LibC.free(ptr)

### ISSUE THREAD

**Issue by scrwr** [ledbettj/systemd-journal#93]
With switching to Ubuntu 21.10 (Systemd 248, glibc version: 2.34) we were running into frequent SIGABRTs.

I hunted down the issue to the LibC.free(ptr) call at:
https://github.com/ledbettj/systemd-journal/blob/master/lib/systemd/journal.rb#L325

From the strace at this point, we can see:
```
[pid 235600] writev(2, [{iov_base="free(): invalid size", iov_len=20}, {iov_base="\n", iov_len=1}], 2) = 21
[pid 235600] mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f9867018000
[pid 235600] rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
[pid 235600] gettid()                   = 235600
[pid 235600] kill(235600, SIGABRT)      = 0
```
Happy to provide further details if required.

**Comment by ledbettj** [comment]
Hi @scrwr, thanks for the report.  I can try to reproduce next week when I'm back home.

Do you happen to know the ruby backtrace where this happens, or which libsystemd function's return value we're handling at this point?  This function is invoked when we need to free memory that was allocated by libsystemd c library, so it's possible that we're missing an error condition or that the contract of one of these functions has changed.

**Comment by scrwr** [comment]
Hi @ledbettj, sure
it comes from:
https://github.com/ledbettj/systemd-journal/blob/master/lib/systemd/journal/navigable.rb#L13

So the pointer is from:  `Native.sd_journal_get_cursor`

**Comment by scrwr** [comment]
Little bit more context as I failed to trigger the SIGABRT in a minimal example so far. So in my case it is triggered from here:
https://github.com/fluent-plugin-systemd/fluent-plugin-systemd/blob/master/lib/fluent/plugin/in_systemd.rb#L151 

The ruby backtrace (caller) before the LibC.free looks like this:
```
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/systemd-journal-1.4.2/lib/systemd/journal/navigable.rb:13:in `cursor'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-systemd-1.0.5/lib/fluent/plugin/in_systemd.rb:151:in `yield_current_entry'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-systemd-1.0.5/lib/fluent/plugin/in_systemd.rb:144:in `watch'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-systemd-1.0.5/lib/fluent/plugin/in_systemd.rb:121:in `run'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.5/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run_once'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.5/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.5/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'

```

**Comment by scrwr** [comment]
Found the issue. Service was loaded with
```
Environment=LD_PRELOAD=/opt/td-agent/embedded/lib/libjemalloc.so
```
After removing, the issue is gone.

**Comment by dg-nvm** [comment]
was there any effort to find an issue here @ledbettj ? We have workaround but it is massive downgrade, given Ruby does not care about memory allocations and jemalloc helps keeping fluentd at bay, especially in K8s environment where limits are strict.

**Comment by ledbettj** [comment]
> was there any effort to find an issue here @ledbettj ? We have workaround but it is massive downgrade, given Ruby does not care about memory allocations and jemalloc helps keeping fluentd at bay, especially in K8s environment where limits are strict.

Hi @dg-nvm! This is being discussed in #96.
